# Generated by Django 3.1.5 on 2021-01-13 17:34

from django.db import migrations, models
import django.db.models.deletion
import django_db_constraints.operations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=18, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InstagramOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes_number', models.PositiveIntegerField(blank=True, null=True)),
                ('subscriptions_number', models.PositiveIntegerField(blank=True, null=True)),
                ('comments_number', models.PositiveIntegerField(blank=True, null=True)),
                ('unsubscribes_number', models.PositiveIntegerField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insta_app.instagramaccount')),
            ],
        ),
        django_db_constraints.operations.AlterConstraints(
            name='InstagramAccount',
            db_constraints={'field_is_not_null': 'CHECK (username IS NOT NULL OR phone_number IS NOT NULL OR email IS NOT NULL)'},
        ),
    ]
